---

- name: 'download Nomad archive'
  get_url:
    dest: '{{hashicorp_dir_staging}}/{{nomad_target}}'
    timeout: '{{hashicorp_internet_timeout}}'
    url: '{{hashicorp_repo}}/nomad/{{nomad_version}}/{{nomad_target}}'
    validate_certs: false
  tags: [ct-nomad]

- name: 'expand archive'
  unarchive:
    src: '{{hashicorp_dir_staging}}/{{nomad_target}}'
    dest: '{{hashicorp_dir_bin}}'
    copy: false
  become: true
  ignore_errors: '{{ansible_check_mode}}'
  tags: [ct-nomad]

- name: 'create CNI directories'
  file:
    state: directory
    path: '{{item}}'
    owner: root
    group: root
    mode: '0775'
  loop: '{{nomad_cni_dirs}}'
  become: true
  tags: [ct-nomad, ct-nomad-cni]

- name: 'download CNI archive'
  get_url:
    url: '{{nomad_cni_url}}'
    dest: '{{nomad_cni_base}}/pkg'
    timeout: '{{hashicorp_internet_timeout}}'
    validate_certs: false
  ignore_errors: '{{ansible_check_mode}}'  # TODO would be good to check the message too
  become: true
  tags: [ct-nomad, ct-nomad-cni]

- name: 'expand CNI archive'
  unarchive:
    src: '{{nomad_cni_base}}/pkg/{{nomad_cni_archive}}'
    dest: '{{nomad_cni_base}}/bin'
    copy: false
  become: true
  tags: [ct-nomad]

- name: 'system account'
  user:
    name: nomad
    comment: 'Nomad system account'
    system: true
    state: present
  become: true
  tags: [ct-nomad]

- name: 'bash include'
  template:
    src: nomad.sh.j2
    dest: /usr/local/etc/bash.d/nomad.sh
    owner: root
    group: root
    mode: 0644
  become: true
  tags: [ct-nomad]

- name: 'directories'
  file:
    state: directory
    path: '{{item}}'
    owner: root
    group: root
    mode: '0755'
  loop: '{{nomad_dirs}}'
  become: true
  tags: [ct-nomad]

- name: '{{nomad_role}} config file'
  template:
    src: '{{nomad_role}}.hcl.j2'
    dest: '{{nomad_etc_dir}}/{{nomad_role}}.hcl'
    backup: true
    owner: root
    group: root
    mode: '0600'
  notify: handler_reload_nomad
  no_log: true
  become: true
  tags: [ct-nomad]

- name: 'systemd unit file'
  template:
    src: nomad-{{nomad_role}}.service.j2
    dest: /etc/systemd/system/nomad-{{nomad_role}}.service
    owner: root
    group: root
    mode: '0644'
  register: reg_service
  become: true
  tags: [ct-nomad]

- name: 'see if Datadog is installed (cm=f)'
  stat:
    path: /etc/datadog-agent
  check_mode: false
  register: doggy
  tags: [ct-nomad, ct-nomad-datadog]

- name: 'render Datadog config file for Systemd'
  template:
    src: datadog-systemd-conf.yaml.j2
    dest: /etc/datadog-agent/conf.d/systemd.d/conf.yaml
    owner: root
    group: root
    mode: '0644'
  when: doggy.stat.isdir is defined and doggy.stat.isdir
  become: true
  tags: [ct-nomad, ct-nomad-datadog]

- name: 'nomad-{{nomad_role}} service to {{nomad_state}}'
  systemd:
    name: nomad-{{nomad_role}}
    state: '{{nomad_state}}'
    enabled: true
    daemon_reload: '{{reg_service is changed}}'
  become: true
  tags: [ct-nomad]

# --------------------------------
...
